name: VKTunnel # <-- Обязательное поле в самом начале файла!

targets:
  # Ваш главный таргет приложения (пример)
  VKTunnel:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [VKTunnel]

  # Таргет расширения
  PacketTunnel:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    sources: [PacketTunnel]
    info:
      path: PacketTunnel/Info.plist
      properties:
        CFBundleDisplayName: PacketTunnel
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
