targets:
  PacketTunnel:
    type: app-extension
    platform: iOS
    sources: [PacketTunnel]
    info:
      path: PacketTunnel/Info.plist
      properties:
        CFBundleDisplayName: PacketTunnel
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
